languageCode = "en"
languageName = "English"
title = "GONDRO"

[params]
  displayName = "EN"
  isoCode = "en"
  dateFormat = "2 January 2006"
  #logo = "img/logo.png"
  #secondaryLogo = "img/secondary-logo.png"
  description = "My awesome website"

[author]
  name = "Gordon Chan"
  #image = "img/blowfish_logo.png"
  headline = "Maths is cool."
  bio = "I love maths."
